analytics: {}
color:
  brandColors:
    - '#C0C8C0'
    - '#043E80'
    - '#5080B0'
    - '#2888F8'
    - '#60B8F8'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.8
name: Roman
opengraph: {}
purpose: []
typography_spectrum: 0.620777
