name: Roman
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.620777
title: The life and growth of Baby Roman W.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C8C0'
    - '#043E80'
    - '#5080B0'
    - '#2888F8'
    - '#60B8F8'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
